name: aj_flutter_plugin
description: A new Flutter plugin.
version: 0.0.1
author: Anji-plus Kean <kean_qi@163.com>
homepage: https://github.com/Keanyuan/aj_flutter_plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.plus.anji.ajflutterplugin
    pluginClass: AjFlutterPlugin
